modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/age-series/ElectricalAge2/issues"

[[mods]]
modId="eln2"
version="${mod_version}"
displayName="${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://age-series.org/"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile=""
credits="The Age Series Team"
authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.eln2]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.eln2]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="1.20"
    ordering="NONE"
    side="BOTH"
